apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels: { app: orders }
  template:
    metadata:
      labels: { app: orders }
    spec:
      containers:
        - name: orders
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8002
          env:
          {{ toYaml .Values.env | nindent 12 }}
          args: ["uvicorn", "services.orders.app:app", "--host", "0.0.0.0", "--port", "8002"]
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: orders
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
