apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels: { app: billing }
  template:
    metadata:
      labels: { app: billing }
    spec:
      containers:
        - name: billing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8003
          env:
          {{ toYaml .Values.env | nindent 12 }}
          args: ["uvicorn", "services.billing.app:app", "--host", "0.0.0.0", "--port", "8003"]
---
apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: billing
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
      protocol: TCP
      name: http
